# Generated by Django 5.2.1 on 2025-05-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_remove_budgetline_budget_remove_budgetline_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='requirement',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='usage',
            field=models.PositiveIntegerField(),
        ),
    ]
