# Generated by Django 5.2.1 on 2025-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_planitem_amount_alter_planitem_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitemtemp',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='planitemtemp',
            name='requirement',
            field=models.PositiveIntegerField(),
        ),
    ]
